version: '2'

services:
  web:
    container_name: arquetipo-web
    image: nginx:1.14.0
    ports:
      - "8080:80"
    volumes:
        - "../:/code"
        - "./nginx/site.conf:/etc/nginx/conf.d/default.conf"
    links:
        - app
        - database
    networks:
        - internal
    depends_on:
        - app
  app:
    container_name: arquetipo-app
    build:
      context: ./php
    networks:
        - internal
    volumes:
        - "../:/code"
    depends_on:
        - database
  database:
    container_name: arquetipo-database
    image: mysql
    environment:
      - "MYSQL_DATABASE=arquetipo_lumen"
      - "MYSQL_USER=arquetipo_lumen_user"
      - "MYSQL_PASSWORD=123456"
      - "MYSQL_ROOT_PASSWORD=123456"
    networks:
      - internal
networks:
  internal: